name: Build Linux Container Image and Push to ACR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: data
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main  # Replace 'main' with the branch or tag name you want to checkout.
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'  # Specify the Node.js version you want to use.
    
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: employeportal.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build and Push Docker image
      run: |
        docker build . -t employeportal.azurecr.io/flask-app:${{ github.sha }}
        docker push employeportal.azurecr.io/flask-app:${{ github.sha }}
